app/abilities/users.js
app/routes/users/members.js
app/routes/users/webdav.js
app/templates/users/webdav.hbs

Made some typo's in the naming of the contact sync

Fix the naming of contactsync

---

app/abilities/membership.js
app/styles/modules/table.scss
app/templates/groups/form.hbs

It is now possible to delete an unsaved membership for users without the membership delete permission.

Delete unsaved memberships

---

app/controllers/photo-albums/photo-album/photos/index.js
app/templates/photo-albums/photo-album/photos/index.hbs

Adds a button to download a zip of the photoalbum. Gives the zip a name containing the date and title of the album in the following format: `YYYY-MM-DD_dasherized-title`.

Add download button for album

---

app/components/boolean-tag.js
app/routes/users/show-settings.js
app/styles/components/page-actions.scss
app/styles/modules/forms.scss
app/templates/components/cards/privacy-preference.hbs
app/templates/components/filter-bar.hbs
app/templates/components/tabbed-view.hbs
app/templates/users/show-groups.hbs
app/templates/users/show-mandates.hbs
app/templates/users/show.hbs

Update the styling on the User pages, fixing multiple errors and glitches. Also tested on mobile.

User page layout fixes

---

app/components/md-editor/md-editor-toolbar.js
app/templates/components/md-editor/md-editor-toolbar.hbs
config/environment.js
package.json
yarn.lock

Fix missing icons in the MD toolbar

Also fix markdown editor toolbar icons

---

app/templates/components/index/index-action-buttons.hbs

updates the 'ik heb interesse' google form to https://docs.google.com/forms/d/e/1FAIpQLSdBkdRWrvv98ZX_JTOMtf9IDtIujHD6SZzxcg5S6JX0slb_zg/viewform?usp=sf_link

Update 'ik heb interesse' google form

---

.buildkite/pipeline.yml
Dockerfile
docker-compose.buildkite.yml

Sentry isn't working anymore. This PR tries to get it working again. I couldn't test it so it is a bit of a gues if it works again after this PR.

Try to get sentry working again

---

app/controllers/oauth/authorize.js
app/routes/oauth/authorize.js
app/templates/oauth/authorize.hbs

This PR makes the UI responsibe for the oauth flow. See the API pr for more information.
I am not glad with the hacky implementation of `clientName` but do not know how to improve this. We need to load this endpoint automatically when this route is loaded, but cannot use the model since the clientName data needs to be available within the controller. It can proabably better but I do not know how. Please give feedback.
Needs: https://github.com/csvalpha/amber-api/pull/52

Improve Oauth

---

app/templates/components/footer-nav.hbs

Update the mobile number to match secretary of board 40

Update contact info to board 40

---

.buildkite/build_npmrc.sh
.gitignore
.npmrc.example
Dockerfile.buildkite
README.md
docker-compose.buildkite.yml
yarn.lock

There are some leftovers from FA pro that are removed by this PR

Remove FA Pro install on buildkite

---

app/controllers/mail-aliases/index.js
app/models/mail-alias.js
app/templates/mail-aliases/index.hbs

This PR adds the last received field to the UI

Add last received field to mail_alias page

---

public/files/user_import_example.csv

The date was formatted inconsistenly, this is now fixed.
The start_study column was missing, which I added.

Fix date example format, add start_study column

---

app/helpers/capitalize-translation.js
app/helpers/capitalize.js
app/templates/articles/show.hbs
app/templates/components/cards/activity-card.hbs
app/templates/components/footer-nav.hbs
app/templates/components/index/index-photos.hbs
app/templates/components/lustrum/lustrum-bar.hbs
app/templates/groups/index.hbs
app/templates/lustrum.hbs
app/templates/static-pages/form.hbs
app/templates/static-pages/index.hbs
config/environment.js

This PR fixes several critical issues with the current staging branch.

Hotfix staging issues

---

app/routes/lustrum.js

I'm pretty sure the lustrum committee has the group id 78. Group 23 is the group "Chess: het spel des levens"

Fix lustrum committee group id

---

app/templates/lustrum.hbs

Bugfix losse aanhalingstekens op lustrum pagina

---

app/templates/articles/show.hbs
app/templates/components/index/index-activities.hbs

Two translator strings were inputted as bare strings

Add missing translator

---

app/templates/components/md-editor.hbs
app/templates/components/md-editor/md-editor-toolbar.hbs

Fix markdown editor

---

app/controllers/groups/edit.js
app/controllers/groups/export.js
app/controllers/oauth/authorize.js
app/controllers/photo-comments/index.js
app/controllers/users/batch/new.js
app/mixins/form-load-or-create-mixin.js
app/models/form/response.js
app/routes/forum/categories/category/threads/thread/posts/index.js
app/routes/oauth/authorize.js
app/templates/oauth/authorize.hbs
tests/helpers/start-app.js
tests/unit/components/form/response/response-form-test.js

Remove some ember 3.6 deprecated code

Remove deprecations

---

app/index.html

The manifest file was not loaded correctly when not on the homepage:

Fix manifest path

---

app/index.html
app/router.js
config/environment.js
package.json
yarn.lock

Currently we use a really outdated package for google analytics. Since it only requires a few lines to push the current page to google analytics I've decided to do this without a package.

Replace analytics

---

app/index.html
app/templates/components/index/index-promo-video.hbs
app/templates/components/youtube-video.hbs
app/templates/index/public.hbs
config/environment.js

This PR implements 2 improvements:
Swap loading of the Nunito fond, this makes sure that the browser first uses the local font and when it becomes available the Nunito font. 
Youtube lazy loading. Currently the youtube image on the homepage blocks it for 600ms. I've implemented a lazy loading mechanism which loads the video as soon as a user clicks on it.

Speed improvements

---

app/templates/index/public.hbs

There is a new promo video, so let's replace it!

Replace promo video

---

app/controllers/sog/name-trainer.js
app/templates/sog/name-trainer.hbs

There was a little bug in the computed trigger for the group, which caused the group not to reload. This PR fixes this.

Hotfix sog page

---

app/styles/components/social-media-buttons.scss
app/styles/variables.scss
app/templates/components/social-media-buttons.hbs
translations/en.yaml
translations/nl.yaml

Add a YouTube button that goes to the YouTube channel of C.S.V. Alpha

Add YouTube social button

---

app/templates/components/menu-sidebar.hbs
config/environment.js
translations/en.yaml
translations/nl.yaml

Add Nextcloud button to menu

---

app/components/advertisement-tool.js

Knaek asked me to update the link on our website.

Update knaek link

---

app/components/page-numbers.js
app/helpers/difference.js
app/styles/components/pagination.scss
app/templates/components/page-numbers.hbs

- Add first page and last page buttons to pagination.
- Show only 5 pages on mobile
Fixes #165

Add first page and last page buttons to pagination.

---

app/components/index/public/youtube-videos.js

This PR adds two new about Alpha videos

Add new videos

---

app/components/advertisement-tool.js

Knaek wants the sponsored image to have a different text.

Update knaek text

---

app/templates/components/footer-nav.hbs

Change phone numbers to new board

---

app/models/activity.js
app/models/article.js
app/models/photo-album.js
app/models/photo.js
app/models/poll.js

This PR fixes several issues that originate from the last PRs of the ember get and new model syntax rewrites

Fix issues related to the ember get rewrites and new model syntax

---

app/models/debit/transaction.js
app/models/form/closed-question-answer.js
app/models/form/closed-question-option.js
app/templates/mail-aliases/show.hbs

Fix issues with mail aliases, polls and collections

Fix several bugs

---

app/abilities/activity.js
app/abilities/article.js
app/abilities/form/response.js
app/abilities/group.js
app/abilities/poll.js
app/controllers/users/index.js
app/models/activity.js
app/models/article.js
app/models/poll.js

Fix edit button of article, activity and poll

---

app/templates/sog/name-trainer.hbs

Fix sog name trainer select

---

app/components/menu-sidebar-item.js
app/styles/components/menu-sidebar.scss

Add menu tooltips

---

.eslintrc.js
app/components/input/select-input.js
app/components/quick-post.js
config/optional-features.json
vendor/message-bus.js

This PR removes jQuery and all uses of it.
See #22

Remove jQuery

---

app/components/advertisement-tool.js
app/styles/components/advertisement-tool.scss
app/templates/components/advertisement-tool.hbs
tests/rendering/components/advertisement-tool-test.js

Advertisement links

---

app/routes/oauth/authorize.js

This PR makes the route for authorizing OAuth applications extend the AuthenticatedRoute.
This PR resolves #271

Fix/Make OauthAuthorizeRoute an AuthenticatedRoute

---

app/adapters/photo-album.js
app/authorizers/oauth2.js
app/helpers/form-opened-label.js
app/helpers/thread-has-new-posts.js
app/serializers/application.js
app/serializers/static-page.js
app/services/fetch.js
app/services/local-storage.js
app/services/message-bus.js
app/services/notification.js
app/session-stores/application.js
app/transforms/capitalized-string.js
app/transforms/raw.js

Let's use more native classes!

More native classes

---

app/abilities/activity.js
app/abilities/article-comment.js
app/abilities/article.js
app/abilities/board-room-presence.js
app/abilities/daily-verse.js
app/abilities/debit/collection.js
app/abilities/debit/mandate.js
app/abilities/debit/transaction.js
app/abilities/form/form.js
app/abilities/form/response.js
app/abilities/forum/category.js
app/abilities/forum/post.js
app/abilities/forum/thread.js
app/abilities/group.js
app/abilities/groups-permission.js
app/abilities/mail-alias.js
app/abilities/mail-moderation.js
app/abilities/member.js
app/abilities/membership.js
app/abilities/permissions-user.js
app/abilities/photo-album.js
app/abilities/photo-comment.js
app/abilities/photo.js
app/abilities/poll.js
app/abilities/quickpost-message.js
app/abilities/sog.js
app/abilities/sog/name-trainer.js
app/abilities/static-page.js
app/abilities/user.js
app/initializers/service-inject.js

This PR migrates all the abilities to use native classes instead of classic ember classes

Make the abilities use native classes

---

app/templates/activities/show.hbs

Fix form signup confirmation

---

app/templates/components/form/response/response-form.hbs

Remove response form debug info

---

app/controllers/mail-moderations/accept.js
app/templates/mail-moderations/accept.hbs

Currently the accept page of mail moderations does not show any errors, this PR fixes that.

Show mail moderation accept errors

---

app/templates/groups/form.hbs

corrects a callback identifier
fixes #362

Fix update group photo

---

.github/workflows/publish-image.yml

fix: use variable instead of value as default for BUILD_HASH

---

app/instance-initializers/intl.js
app/routes/application.js

Dates were always shown in English, regardless of locale. This PR fixes that.

Fix localization of moment dates

---

tests/unit/routes/groups/edit-test.js
tests/unit/routes/polls/destroy-test.js
tests/unit/routes/polls/edit-test.js
tests/unit/routes/polls/index-test.js
tests/unit/routes/polls/new-test.js
tests/unit/routes/polls/show-test.js
tests/unit/routes/users/edit-test.js

Maybe I'm missing something, but there seem to be some duplicate tests that don't add anything. I have de-duplicated those. It might be the result of some merge.

Fix duplicate tests

---

app/components/cards/frontpage-activity-card-small.js
app/components/index/public/activities.js
app/components/index/public/background-image.js
app/components/index/special-promo.js
app/components/quick-post.js
app/controllers/polls/show.js

refactor: import htmlSafe from @ember/template

---

app/templates/groups/index.hbs

Fix: groups dropdown input

---

.github/workflows/continuous-integration.yml
.github/workflows/publish-image.yml

Fixes the actionlint errors from #576 by ignoring the error message.

fix: actionlint errors on non-existing context in some events

---

app/components/model-form/file-input.hbs

Fix code in file-upload.hbs using deprecated components

---

app/components/index/public/activities.js

Fix image banner on activity cards not updating

---

config/environment.js

Fixes #638 
Related: https://github.com/adopted-ember-addons/ember-moment/issues/375
Might need to be reverted if https://github.com/adopted-ember-addons/ember-moment/pull/383 is ever merged, however the PR is already open since July.

Fix ember-moment config

---

app/components/cards/activity-card.hbs
app/components/form/consumption-list.hbs
app/components/form/responses-table-row.hbs
app/components/forms/group-form.hbs
app/components/forms/mail-alias-form.hbs
app/components/forms/user-form.hbs
app/components/forum/forum-post.hbs
app/components/forum/forum-post.js
app/components/photo-albums/photo.hbs
app/components/quick-post.hbs
app/components/tools/board-room-presence.hbs
app/components/tools/upcoming-birthdays.hbs
app/components/user-comment.hbs
app/controllers/groups/export.js
app/controllers/sog/name-trainer.js
app/models/user.js
app/templates/forum/categories/category/threads/index.hbs
app/templates/forum/categories/category/threads/thread/posts/destroy.hbs
app/templates/forum/categories/index.hbs
app/templates/groups/show.hbs
app/templates/mail-aliases/index.hbs
app/templates/mail-aliases/show.hbs
app/templates/polls/show.hbs
app/templates/sog/name-trainer.hbs
app/templates/users/destroy.hbs
app/templates/users/index.hbs
app/templates/users/members.hbs
app/templates/users/resend-activation.hbs
app/templates/users/show.hbs
mirage/factories/user.js

Adds a nickname field to the website.
Currently, some people have the nickname in brackets behind their first name. This PR will give a more robust solution for nicknames.
See https://github.com/csvalpha/amber-api/pull/346 and https://github.com/csvalpha/sofia/pull/833

Add nicknames

---

app/controllers/users/destroy.js
app/routes/users/show.js

Fix: remove non-existing user destroy endpoint

---

app/transforms/date-only.js

Fix date when null

---

app/controllers/vacancies/index.js

Added 'sort' to the query params to order vacancies from newest added to oldest added

fixed vacancies ordering

---

translations/en.yaml
translations/nl.yaml

Update interested text

---

app/components/tools/daily-verse.hbs
app/components/tools/daily-verse.js

Add camel jokes for sine regno

Add camel jokes

---

package.json
yarn.lock

Fixes not being able to select a date in date inputs anymore. This reverts [https://github.com/csvalpha/amber-ui/pull/715](https://github.com/csvalpha/amber-ui/pull/715)

fixed new ember-power-select version breaking pika date selections

---

app/components/tools/daily-verse.hbs
app/components/tools/daily-verse.js

Revert "Add camel jokes"

---

app/styles/app.scss
app/styles/routes/groups.scss
app/templates/groups/show.hbs

fixed bounding of group photos

---

app/components/form/responses-table-card.hbs
app/components/form/responses-table-card.js

Add copy usernames button to activity responses table

---

app/index.html
app/styles/components/public/index/about-alpha.scss
app/styles/routes/public/index.scss
translations/en.yaml
translations/nl.yaml

Changed a font and the title of the video section on the public side of the site

changed a font and title of video section

---

app/styles/components/navbar.scss

Old:
New:
Fixed by making the container a flex-box

Fixed over-ons dropdown too wide on public site

---

app/components/form/responses-table-card.js

request from a user per email:
> Goedemiddag ICT,
> 
>  
> 
> Eerder heb ik met Wilco contact gehad over de knop ‘kopieer gebruikersnamen’. Deze werkt voortreffelijk. Alleen plakt het ook altijd mijn eigen gebruikersnaam bij de lijst, ook al ben ik niet ingeschreven. Zouden jullie dit eventueel kunnen oplossen?
> 
>  
> 
> Mijn dank is alvast weer groot.

Fix: do not copy own username if no completed response

---

app/components/menu-sidebar.hbs
app/routes/profile.js
app/routes/users/user.js
app/routes/users/user/index.js

fixes #802
fixes #784 
Tested both show and edit
After merging this, we should let the old-members that emailed us know that this is fixed. See mailbox for who those people are

Fix: access to profile

---

app/components/photo-tags/photo-tags.js

Fix tag requires double click after first tag

---

.github/workflows/continuous-integration.yml
README.md
ember-cli-build.js
mirage/config.js
package.json
tests/test-helper.js
yarn.lock

Reverts csvalpha/amber-ui#817
Breaks actions with the error `The workflow is not valid. .github/workflows/continuous-delivery.yml (Line: 105, Col: 11): Secret codecov_token is required, but not provided while calling.`

Revert "feat(tests): add code coverage reporting"

---

app/components/header-nav.js

self-descriptive. probably broke in #804

Fix: sidebar toggle on mobile

---

config/environment.js

I made a caps error in a recent PR

hotfix sofiaURL

---

app/components/cards/privacy-preference.hbs
app/components/privacy-modal.hbs
app/components/privacy-modal.js
app/components/users/privacy-settings.hbs
app/models/user.js

accompaning PR for https://github.com/csvalpha/amber-api/pull/507
requires https://github.com/csvalpha/amber-api/pull/507

Add question if user has BE rijbewijs

---

app/components/cards/privacy-preference.hbs
app/components/forms/user-form.hbs
app/components/users/privacy-settings.hbs
app/controllers/groups/group/export.js
app/models/user.js
app/templates/users/user/index.hbs
app/templates/users/user/settings.hbs

Fixes https://github.com/csvalpha/amber-api/issues/524 & https://github.com/csvalpha/amber-api/issues/424
I also sorted the user model a bit better
requires https://github.com/csvalpha/amber-api/pull/528

make sidekiq UI modifiable & Be rijbewijs improvements

---

app/controllers/groups/group/export.js

i accedentiely used camelCase instead of snake_case

Hotfix user export

---

app/components/privacy-modal.hbs
app/controllers/groups/group/export.js

fixes https://github.com/csvalpha/amber-ui/issues/958

Hotfix for wrong merge

---

app/components/users/otp-settings.hbs

Hotfix otp secret generator

---

app/styles/app.scss

Remove lustum theme

---

app/constants.js
app/controllers/groups/index.js

We just voted to make a Zal at the ALV so we need the group type
Links to https://github.com/csvalpha/amber-api/pull/566

Introduce Zal group type

---

app/components/users/password-settings.hbs

revert to using action helper in password settings

Fix the wachtwoord wijzigen knop

---

app/components/form/responses-table-card.hbs
app/models/form/form.js

sorted form responses

---

app/components/tools/board-room-presence.js
app/components/tools/study-room-presence.hbs
app/components/tools/study-room-presence.js

This update makes it so you could set your state to chilling which was buggy in the past
And it also added the colored dot next to the text which was missing due to a typo
Solves https://github.com/csvalpha/amber-ui/issues/931

Fix small errors in the implementation of the tweede kamer button

---

.github/workflows/continuous-integration.yml
.github/workflows/publish-image.yml
app/components/public/index/header.js
config/environment.js

Makes it so the form looks nicer and is easier to change after each year

Improve form geintresserde

---

app/components/filter-bar.hbs
app/components/filter-bar.js
app/components/photo-tags/photo-tags.js
app/styles/components/navbar.scss
app/styles/components/page-actions.scss

Solves https://github.com/csvalpha/amber-ui/issue/982 make menu button fully visible
Solves https://github.com/csvalpha/amber-ui/issue/911 change phototag centerlocation
In progress search button on mobile
TO DO

General improvement

---

app/components/forms/activity-form.hbs
app/components/users/otp-settings.hbs

Fix another button around 2fa
