csvalpha/amber-ui

- app/instance-initializers/i18n.js
Because our statistics show that the majority of our users speakes the dutch language, and wants to use the site in dutch, but a large part of those users has a english locale as device default. This means a lot of people have a incorrect locale when visiting the site. Therefore it now defaults to dutch and remembers your choice if changed.
> Default external locale to dutch

- app/templates/users/webdav.hbs
It appeared that the contact sync info was not clear. This PR makes the text about where to find bold.
> Make contactsync more clear

- app/initializers/register-showdown-extensions.js
There where some issues with the youtube regex. I found out the issue was that when a URL was before the youtube this screwed to regex. The Issue was that the regex identified the url as youtube. This PR probably fixed it.
> Fix the youtube regex

- .buildkite/build_npmrc.sh
- Dockerfile
~I'm trying to figure out why CI is not working for branch staging~
The Dockerfile.buildkite was good, but the (production) Dockerfile missed the npmrc script so the FontAwesome5 packages would not load correctly (401 unauthorized)
> Add npmrc file script to production dockerfile 

- app/styles/components/forum/forum-post.scss
- app/templates/components/forum/forum-post.hbs
Makes the icon-buttons under the forum posts behave normally again
> Fix the forum post icons from being huge and off-page

- app/initializers/register-showdown-extensions.js
- tests/unit/helpers/youtube-regex-test.js
See issue #39
This PR fixes the problem where the youtube regex would match urls that weren't youtube urls by making sure that the url is from the domain youtube(.com) or youtu(.be).
> Fix youtube regex

- app/components/quick-post.js
wrong name for a json attribute was used
I noticed a loadMore function in app/components/quick-post.js which I found odd since I hadn't seen any load more button on the webpage recently, so I managed to locate the problem, being the use of the wrong name for a the json attribute, namely "meta.total-pages" instead of the correct name "meta.page_count"
> Load more button was not visible

- app/serializers/application.js
The 'closing activity' tool is broken. It loads the data and calls a 'pushPayload'. This is not serialized by `normalizeReponse` but it is by `normalize`, so I changed the logic to that method. 
The 'closing indicator' still shows wrong values sometimes but I cannot find why. At least the link is working again
> Hotfix activity link

- app/routes/users/index.js
This PRs makes the users page only show not archived users
Needs: https://github.com/csvalpha/amber-api/pull/102
> Only show not archived users

- app/templates/index/authenticated.hbs
It is not useful for members to see closing activities if they cannot enroll for activities. I removed this tool for people without the create form/responses permission
See #63
> Remove closing activities for members without create form/responses permission

- app/templates/components/cards/article-card.hbs
Before, the "Meer lezen" button was visible on the page with all the articles and on an article's page itself. When you clicked the button on the articles page, it routes you to the page of the article and when you clicked the button on the article's page itself, it routes to itself. Thus it's unnecessary to have the read more button visible on the article's page and this PR hides it.
> Hide read more button in article-card's big view

- app/templates/users/form.hbs
Currently the user form has no requirement on the email, but this is required. Also the username attribute is present, but we do want to users to set this manually, this is autogenerated by the API.
> Hide username and make email required

- translations/en.yaml
- translations/nl.yaml
The capitalization of the menu items was inconsistent. This PR only makes the first letter of each menu item uppercase.
> Make all menu items first-letter uppercase only

- app/components/header-nav.js
Ember would not load because the lustrum page commit was merged without updating i18n to intl.
> Fix i18n issue with lustrum page

- app/routes/application.js
- config/ember-intl.js
Ember Intl defaults to en-us, however we do not have that translation (since we use en). So this PR sets the default to nl which fixes the translations.
I also found a method to let the build fail when locals are missing, I enabled this to prevent missing locals (not really relevant to this bug, but it might be usefull)
> Set local to default nl

- app/templates/activities/index.hbs
- app/templates/components/tools/closing-activities.hbs
- app/templates/components/tools/recent-polls.hbs
- app/templates/components/tools/upcoming-activities.hbs
When clicking on an activity or poll on the front page or clicking on an activity in the activities page, it showed a blank page. This PR fixes that.
> Fix activity and poll loading

- app/models/article.js
- app/templates/components/cards/article-card.hbs
- app/templates/components/cards/frontpage-article-card.hbs
- app/templates/components/index/index-action-buttons.hbs
- app/templates/components/index/index-activities.hbs
- app/templates/components/index/index-stories.hbs
- app/templates/components/tools/static-pages.hbs
- translations/en.yaml
- translations/nl.yaml
This PR has several bugfixes for the external front page
- Author name and image thumb not showing on articles
- Static pages list not loading
- Update Google Forms to forms linked to the ICT Committee Google account
- Add a button to Studiegids.nl since they asked
- Add a bit more space between the ads and stories
- Add translation for the button at the top of the page
Requires API PR [#147](https://github.com/csvalpha/amber-api/pull/147)
> Update external site

- app/controllers/photo-albums/photo-album/edit.js
- app/services/message-bus.js
- config/environment.js
Fixes #150 
Also, there was no preview shown of the uploaded images because it is shown as a base64 encoded data string which was not allowed by cors policy. That is also fixed with this PR.
> Fix dropzone

- translations/en.yaml
The translations for the about Alpha and about Flux section are switched around on the English site. This PR fixes that.
> Fix about Alpha and about Flux texts switched around

- app/models/activity.js
- app/models/debit/collection.js
- app/models/debit/mandate.js
- app/models/debit/transaction.js
- app/models/form/closed-question-answer.js
- app/models/form/closed-question-option.js
- app/models/form/closed-question.js
- app/models/form/form.js
- app/models/form/open-question-answer.js
- app/models/form/open-question.js
- app/models/forum/post.js
- app/models/forum/thread.js
- app/models/group.js
- app/models/mail-alias.js
- app/models/membership.js
- app/models/photo-comment.js
- app/models/photo.js
- app/models/poll.js
- app/models/quickpost-message.js
- app/models/static-page.js
- app/models/stored-mail.js
- app/models/user.js
There were several issues with the last deploy. This PR fixes that: 
- Users could not be added to a group because of an incomplete model relation
- Date attributes were not parsed as dates. This caused user group filtering to be broken and may have caused other issues elsewhere
> Fix model relations and date attributes

- app/templates/activities/ical.hbs
Fixes #215 
I just removed the button, since all the checkboxes are checked by default anyways.
> Fix broken select all button on iCal page 

- app/controllers/sog/name-trainer.js
- app/styles/routes/sog/name-trainer.scss
- app/templates/sog/name-trainer.hbs
This PR improves the layout of the Easy name trainer level by showing the images in a 2x2 grid instead of a list.
Additionally, users without an avatar image are now filtered from the trainer.
> Remove users without thumbnail from list, improve difficulty 1 layout

- app/routes/forum/categories/category/threads/thread.js
#262 introduced a regression where a wrong permission was being used for showing threads.
This PR resolves #267
> Fix thread permission bug

- app/templates/activities/form.hbs
- app/templates/articles/form.hbs
- app/templates/debit/collections/edit.hbs
- app/templates/mail-aliases/form.hbs
- app/templates/users/batch/new.hbs
Currently we cannot unset a lot of the 'Power selectors', while for some we need to be able to do it. I have added the `allowClear` option to the selectors for which I think it is useful to be able to unset the selection.
Fixes #245
> Allow clearing the powerselectors

- app/services/session.js
Fixes #281 
The Oauth route does an redirect as soon as it sees that the current user has already authorized the application. However, this throws an 'abortError' in ember, which just indicates that the current transition has been aborted. This however combined with the loadUser caused it to invalidate. this PR fixes that by checking that the error is not an abortError
> Fix abort error on oauth after login

- app/components/form/response/response-form.js
The optionIds are updated later than updateMultipleChoiceAnswers is called, causing selected form options to lag behind. The form elements should be rewritten but for now, adding a small timeout works as a hotfix.
> Hotfix for form signup

- docker-compose.buildkite.yml
After merging https://github.com/csvalpha/amber-ui/pull/315 I found out that the `deployTarget` is not correctly set (because after deploying that PR it sent the production `client_id` instead of the staging one on staging).
This is the case because in the Dockerfile, the ARG `DEPLOY_TARGET` defaults to "production" and instead of setting the build args in `docker-compose.buildkite.yml` it sets env variables, so the ARG in the Dockerfile is never overridden.
This PR fixes that by correctly setting the build args.
> fix: correctly set build args in docker-compose build config

- app/routes/debit/collections/sepa.js
Related: #290 
When trying to export a sepa the error `this.saveFileAs is not a function` would be shown.
> Fix sepa saving

- app/routes/users/resend-activation.js
- app/templates/users/resend-activation.hbs
When a user is not activated yet, the user detail page does not load because of an error in the route of resend_activation. This PR hotfixes this.
> Hotfix user detail page

- app/components/poll/closed-question.js
- package.json
- yarn.lock
After the mixins PR was reviewed, a staging into PR branch merge commit (36c67015201e3094dc6ec8ef4962e85bf82019e3) somehow removed `file-saver` from the dependencies. I'm very confused as to why this happened, this PR adds it again!
> fix: install file-saver and extend instead of reexport component

- app/routes/users/index.js
Because of https://github.com/csvalpha/amber-api/pull/259 there is no need to filter out archived users anymore.
> Fix archived user filter

- app/controllers/application/destroy.js
When you destroy a model (e.g. activity), currently it does not redirect you back to the index of that model, but instead it stays on the destroy confirmation page. This PR fixes that.
> Fix redirect after destroy

- config/content-security-policy.js
This PR adds `data:` to the list of allowed `img-src`s in the CSP such that the base64 data images in e.g. the article cover upload preview can be shown. Since this only allows inline data in img context this should pose no inherent security risk.
Before fix:
After fix it previews the uploaded image.
> Add data: to img-src in CSP

- .github/renovate.json5
I missed a few dependencies that are handled by `ember-cli-update` in #469 and also the Renovate PRs include resolutions updates. This PR fixes both problems.
> fix: add missing deps to ignore and disable resolution updates

- package.json
- yarn.lock
Downgrades ember-data down a minor version because we're experiencing some problems with `3.28.x`.
> fix: downgrade ember-data

- .github/renovate.json5
Makes the Renovate configuration extend the base configuration hosted in https://github.com/csvalpha/.github/blob/main/default.json
> feat: extend base renovate configuration

- package.json
`yarn lint:fix` didn't find any scripts matching the regex `lint:*:fix` because the regex wasn't put into quotes. Tested this fix and it works for my machine
> add escaped quotes to command

- .template-lintrc.js
- app/components/index/public/potential-member-section.hbs
- app/helpers/html-safe.js
Fixes #536.
Also removed some rules from `.template-lintrc.js` as they are already enabled in the `recommended` configuration that ours is extending.
> fix: mark potential member info as htmlSafe

- .github/renovate.json5
- mirage/factories/activity.js
- mirage/factories/article-comment.js
- mirage/factories/article.js
- mirage/factories/daily-verse.js
- mirage/factories/debit-collection.js
- mirage/factories/debit-transaction.js
- mirage/factories/form-closed-question-option.js
- mirage/factories/form-closed-question.js
- mirage/factories/form-form.js
- mirage/factories/form-open-question-answer.js
- mirage/factories/form-open-question.js
- mirage/factories/forum-category.js
- mirage/factories/forum-post.js
- mirage/factories/forum-thread.js
- mirage/factories/group.js
- mirage/factories/membership.js
- mirage/factories/photo-album.js
- mirage/factories/photo-comment.js
- mirage/factories/quickpost-message.js
- mirage/factories/static-page.js
- mirage/factories/user.js
- package.json
- yarn.lock
Updates `faker` to its official fork, `@faker-js/faker`.
https://github.com/faker-js/faker
> chore(deps): update faker to official fork

- translations/en.yaml
- translations/nl.yaml
Apparently Github only does full-word search, so I missed these phone numbers when updating the abactis phone number
> Update message phone number

- .github/renovate.json5
- package.json
- yarn.lock
After #621 ember-cli used to build the project locally is out of sync with the ember-cli version used in the Docker container. This PR changes the PR body on ember-cli patch updates so that the wait instruction is included here too.
> fix(renovate.json5): add wait instruction to ember-cli patch PRs too

- app/components/forum/forum-post-new.hbs
- app/components/forum/forum-post-new.js
- app/controllers/forum/categories/category/threads/thread/posts/index.js
- app/templates/forum/categories/category/threads/thread/posts/index.hbs
ref #641 
rewrote to glimmer component, because I understand them better, and it allows me to use the `this.args` namespace (see https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/#toc_benefits-of-glimmer-components)
note that args are immutable in glimmer components, which requires an extra function to be passed as an argument. Via this function `onChangeContent` we can pass the new value up to the containing controller, in this case `posts/index`
(If you're familiar with Vue.js then this pattern should look familiar.)
This would be fixed when #539 is finished, but I thought it wouldn't hurt to fix this since creating forum post is still broken right now
> Ameliorate forum-post-new reactivity

- app/components/footer-nav.hbs
Often, the phone number of Flux is called when somebody wants to contact Alpha. This PR replaces the contact info of flux with a link to the website of Flux, so that the differentiation Alpha<>Flux is hopefully a bit clearer.
> Update Flux contact info in footer

- app/controllers/activities/edit.js
Activity forms currently always show an empty error if there is no error. This PR fixes that
> Fix error in activity always showing

- app/templates/activities/destroy.hbs
- app/templates/polls/destroy.hbs
There was code in the templates that did not show the deletion button in the deletion confirmation winow if the acctivity or poll has responses. However, that code did not work anymore and we decided we did not want this behaviour anyways. So the code was removed.
> Removed deletion blocking when activity or poll has responses

- package.json
- yarn.lock
This reverts commit 7f4f85b7cae41779f664337f5f19627fc9fcbd3e (https://github.com/csvalpha/amber-ui/pull/751).
Turns out ember-async-data was used for something, since the overview of acitvity signups is now  broken. This PR should fix that.
> Revert "Remove unused ember-async-data package (#751)"

- package.json
- yarn.lock
Currently, building Ember fails because of problems with source-map on Node 18. This PR fixes that. See https://github.com/ef4/fast-sourcemap-concat/pull/66 for more information. That PR is not in a named release of fast-sourcemap-concat yet, so for now, we change the resolution of fast-sourcemap-concat to the specific commit on its Github repo that fixed this issue
> Fix node 18 problems

- app/routes/activities/activity/index.js
I think this fixes the following issue (I recently deleted this line):
> fix problem with loading current response

- app/abilities/user.js
- app/components/menu-sidebar.hbs
- app/routes/profile.js
Turns out this broke in #805  . Reproduced locally, the problem only occurs right after login, any refresh already worked around the issue.
> Fix sidebar rendering (for old-members)

- app/routes/sog/index.js
- app/styles/app.scss
- app/styles/components/list-group.scss
- app/templates/sog/index.hbs
Fixes #864 
Requires https://github.com/csvalpha/amber-api/pull/432
> Add content to SOG page

- app/components/cards/photo-album-card.hbs
- app/models/photo-album.js
- app/styles/components/cards/photo-album-card.scss
- app/styles/routes/photos.scss
- app/templates/photo-albums/photo-album/photos/index.hbs
- tests/unit/models/photo-album-test.js
- yarn.lock
(Issue#870) A small tag is added to the photo album cover cards, the number of photos that have been tagged out of the total amount of photos.
The tag does not show up for albums in which none of the photos have been tagged or that do not contain any photos.
The goal is to provide an easy way to check if the photos in the album have been tagged.
(Issue#863) The similar issue is fixed by also displaying the tag count of each photo in the same  box as the comment count.
> album tag counter

- config/environment.js
I reseeded staging, found out that's not how things are supposed to be done, and ended up creating a new doorkeeper application, so we need to update the client id here
> Fix: update doorkeeper client id

- .github/workflows/cleanup-registry.yml
`GITHUB_TOKEN` in pipelines can delete package versions on ghcr now, this PR moves the Cleanup Registry workflow to using an official action that also defaults to using this token.
> refactor(cleanup-registry): use new action

- app/routes/debit/collections/collection/sepa.js
A small change in file extension is needed for https://github.com/csvalpha/amber-api/pull/489 to work.
> Split incasso in multiple SEPA files

- app/components/cards/privacy-preference.hbs
- app/components/privacy-modal.hbs
- app/components/privacy-modal.js
- app/components/users/privacy-settings.hbs
- app/models/user.js
> Revert "Add question if user has BE rijbewijs"

- app/controllers/groups/group/export.js
Fixes https://github.com/csvalpha/amber-ui/issues/940
I removed the ability to download all IBAN because it is not stored in the user table but in the mandates table. besides that it is really sensitive data.
If we need this functionality we need to a export button to the mandates tab or fix it some other way
> Remove IBAN option from group export

- app/templates/photo-albums/photo-album/photos/index.hbs
Solves https://github.com/csvalpha/amber-ui/issues/978
This is being removed because it looked really ugly and there is no need for a public person to view all photos one by one
> Remove ability to view a photo when not logged in
